<?php

/**
 * BaseType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Attendees_T
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getAttendeesT()  Returns the current record's "Attendees_T" collection
 * @method Type                setName()        Sets the current record's "name" value
 * @method Type                setAttendeesT()  Sets the current record's "Attendees_T" collection
 * 
 * @package    kickboxing
 * @subpackage model
 * @author     Derek Organ
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Attendee as Attendees_T', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}