<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property integer $sf_guard_user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property string $country
 * @property Event $Event
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $Attendees_P
 * 
 * @method integer             getEventId()          Returns the current record's "event_id" value
 * @method integer             getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method string              getFirstName()        Returns the current record's "first_name" value
 * @method string              getLastName()         Returns the current record's "last_name" value
 * @method string              getEmailAddress()     Returns the current record's "email_address" value
 * @method string              getCountry()          Returns the current record's "country" value
 * @method Event               getEvent()            Returns the current record's "Event" value
 * @method sfGuardUser         getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getAttendeesP()       Returns the current record's "Attendees_P" collection
 * @method Profile             setEventId()          Sets the current record's "event_id" value
 * @method Profile             setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Profile             setFirstName()        Sets the current record's "first_name" value
 * @method Profile             setLastName()         Sets the current record's "last_name" value
 * @method Profile             setEmailAddress()     Sets the current record's "email_address" value
 * @method Profile             setCountry()          Sets the current record's "country" value
 * @method Profile             setEvent()            Sets the current record's "Event" value
 * @method Profile             setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method Profile             setAttendeesP()       Sets the current record's "Attendees_P" collection
 * 
 * @package    my_derek
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasMany('Attendee as Attendees_P', array(
             'local' => 'id',
             'foreign' => 'profile_id'));
    }
}