<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Event', 'doctrine');

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property date $start
 * @property date $end
 * @property date $register_by
 * @property Doctrine_Collection $EventDiscipline
 * @property Profile $Profile
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method date                getStart()           Returns the current record's "start" value
 * @method date                getEnd()             Returns the current record's "end" value
 * @method date                getRegisterBy()      Returns the current record's "register_by" value
 * @method Doctrine_Collection getEventDiscipline() Returns the current record's "EventDiscipline" collection
 * @method Profile             getProfile()         Returns the current record's "Profile" value
 * @method Event               setId()              Sets the current record's "id" value
 * @method Event               setName()            Sets the current record's "name" value
 * @method Event               setDescription()     Sets the current record's "description" value
 * @method Event               setStart()           Sets the current record's "start" value
 * @method Event               setEnd()             Sets the current record's "end" value
 * @method Event               setRegisterBy()      Sets the current record's "register_by" value
 * @method Event               setEventDiscipline() Sets the current record's "EventDiscipline" collection
 * @method Event               setProfile()         Sets the current record's "Profile" value
 * 
 * @package    my_derek
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('start', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('register_by', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EventDiscipline', array(
             'local' => 'id',
             'foreign' => 'event_id'));

        $this->hasOne('Profile', array(
             'local' => 'id',
             'foreign' => 'event_id'));
    }
}