<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property integer $attendant_id
 * @property integer $event_id
 * @property string $first_name
 * @property string $middle_name
 * @property string $last_name
 * @property string $email_address
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $Attendee
 * 
 * @method integer             getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method integer             getAttendantId()      Returns the current record's "attendant_id" value
 * @method integer             getEventId()          Returns the current record's "event_id" value
 * @method string              getFirstName()        Returns the current record's "first_name" value
 * @method string              getMiddleName()       Returns the current record's "middle_name" value
 * @method string              getLastName()         Returns the current record's "last_name" value
 * @method string              getEmailAddress()     Returns the current record's "email_address" value
 * @method sfGuardUser         getUser()             Returns the current record's "User" value
 * @method Doctrine_Collection getEvent()            Returns the current record's "Event" collection
 * @method Doctrine_Collection getAttendee()         Returns the current record's "Attendee" collection
 * @method Profile             setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Profile             setAttendantId()      Sets the current record's "attendant_id" value
 * @method Profile             setEventId()          Sets the current record's "event_id" value
 * @method Profile             setFirstName()        Sets the current record's "first_name" value
 * @method Profile             setMiddleName()       Sets the current record's "middle_name" value
 * @method Profile             setLastName()         Sets the current record's "last_name" value
 * @method Profile             setEmailAddress()     Sets the current record's "email_address" value
 * @method Profile             setUser()             Sets the current record's "User" value
 * @method Profile             setEvent()            Sets the current record's "Event" collection
 * @method Profile             setAttendee()         Sets the current record's "Attendee" collection
 * 
 * @package    my_derek
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('attendant_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('event_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('middle_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasMany('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasMany('Attendee', array(
             'local' => 'attendant_id',
             'foreign' => 'id'));
    }
}