<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Discipline', 'doctrine');

/**
 * BaseDiscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property enum $sex
 * @property Doctrine_Collection $Division
 * @property Doctrine_Collection $EventDiscipline
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method enum                getSex()             Returns the current record's "sex" value
 * @method Doctrine_Collection getDivision()        Returns the current record's "Division" collection
 * @method Doctrine_Collection getEventDiscipline() Returns the current record's "EventDiscipline" collection
 * @method Discipline          setId()              Sets the current record's "id" value
 * @method Discipline          setName()            Sets the current record's "name" value
 * @method Discipline          setSex()             Sets the current record's "sex" value
 * @method Discipline          setDivision()        Sets the current record's "Division" collection
 * @method Discipline          setEventDiscipline() Sets the current record's "EventDiscipline" collection
 * 
 * @package    registration
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiscipline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('discipline');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('sex', 'enum', 6, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Male',
              1 => 'Female',
             ),
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Division', array(
             'local' => 'id',
             'foreign' => 'discipline_id'));

        $this->hasMany('EventDiscipline', array(
             'local' => 'id',
             'foreign' => 'discipline_id'));
    }
}