<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Discipline', 'doctrine');

/**
 * BaseDiscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property enum $sex
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $Divisions_Disc
 * @property Doctrine_Collection $EventDisciplines
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method enum                getSex()              Returns the current record's "sex" value
 * @method Doctrine_Collection getEvent()            Returns the current record's "Event" collection
 * @method Doctrine_Collection getDivisionsDisc()    Returns the current record's "Divisions_Disc" collection
 * @method Doctrine_Collection getEventDisciplines() Returns the current record's "EventDisciplines" collection
 * @method Discipline          setName()             Sets the current record's "name" value
 * @method Discipline          setSex()              Sets the current record's "sex" value
 * @method Discipline          setEvent()            Sets the current record's "Event" collection
 * @method Discipline          setDivisionsDisc()    Sets the current record's "Divisions_Disc" collection
 * @method Discipline          setEventDisciplines() Sets the current record's "EventDisciplines" collection
 * 
 * @package    my_derek
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiscipline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('discipline');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('sex', 'enum', 6, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Male',
              1 => 'Female',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Event', array(
             'refClass' => 'EventDiscipline',
             'local' => 'discipline_id',
             'foreign' => 'event_id'));

        $this->hasMany('Division as Divisions_Disc', array(
             'local' => 'id',
             'foreign' => 'discipline_id'));

        $this->hasMany('EventDiscipline as EventDisciplines', array(
             'local' => 'id',
             'foreign' => 'discipline_id'));
    }
}