<?php

/**
 * Division
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    my_derek
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Division extends BaseDivision
{
    public function __toString()
    {
        return $this->getDiscipline()->getName() . " " . $this->getDiscipline()->getSex() . " - " . $this->category . ", " . $this->weight;
        
        //{discipline.name discipline.sex - division.category division.weight}
    }
}