<?php

/**
 * DivisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DivisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DivisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Division');
    }
}