<?php

/**
 * EventDisciplineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventDisciplineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventDisciplineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventDiscipline');
    }
}