<?php

/**
 * TeamAdministratorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamAdministratorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamAdministratorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamAdministrator');
    }
}