# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

atten:
  url:   /attendee
  param: { module: attendee, action: index }

atten_edit:
  url:   /attendee/edit/:id
  param: { module: attendee, action: edit }

atten_update:
  url:   /attendee/update/:id
  param: { module: attendee, action: update }

atten_delete:
  url:   /attendee/delete/:id
  param: { module: attendee, action: delete }

atten_new:
  url: attendee/new
  param: { module: attendee, action: new }
atten_create:
  url: attendee/create
  param: { module: attendee, action: create }



sf_guard_register:
  url:   /register
  param: { module: sfGuardRegister, action: index }


sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }




homepage:
  url:   /
  param: { module: sfGuardAuth, action: signin }

# generic rules
# please, remove them by adding more specific rules
#default_index:
  #url:   /:module
  #param: { action: index }

#default:
  #url:   /:module/:action/*
