generator:
  class: sfDoctrineGenerator
  param:
    model_class:           attendee
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          attendee
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:
        class: BackendAttendeeForm
      edit:    ~
        #display:
          #'Attendee Information': [ profile_id, division_id, type_id, first_name, last_name, sex, club_name, accomodation, sharing_with1, sharing_with2, flight_datetime, flight_time, flight_number, visa, dob, passport, expiry_date ]
      new:     ~
