all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=_kickboxing'
      username: kickboxing
      password: k1ckb0x
dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:dbhost=localhost; dbname=_kickboxing_dev'
      username: root
      password: wh1stl3r
