<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('event', 'token', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('event', 'token');
    }
}