<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprofile extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'event_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'sf_guard_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'email_address' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'country' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('profile');
    }
}