<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addeventdiscipline extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('event_discipline', array(
             'event_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'discipline_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'event_id',
              1 => 'discipline_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('event_discipline');
    }
}