<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addevent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('event', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'text',
              'length' => NULL,
             ),
             'starts' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'ends' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'register_by' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('event');
    }
}