#NEW SCHEMA
##########

Attendee:
  connection: doctrine
  tableName: attendee
  columns:
    profile_id:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    division_id:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    type_id:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    first_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    last_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sex:
      type: enum(6)
      fixed: false
      unsigned: false
      values:
        - Male
        - Female
      primary: false
      notnull: false
      autoincrement: false
    club_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    accomodation:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sharing_with1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sharing_with2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    flight_datetime:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    flight_time:
      type: time
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    flight_number:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    visa:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    dob:
      type: date(25)
      notnull: false
    passport:
      type: string(255)
      notnull: false
    expiry_date:
      type: date(25)
      notnull: false      
  relations:
    Division:
        foreignAlias: Attendees_Div
    Type:
        foreignAlias: Attendees_T
    Profile:
        foreignAlias: Attendees_P



Discipline:
  connection: doctrine
  tableName: discipline
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sex:
      type: enum(6)
      fixed: false
      unsigned: false
      values:
        - Male
        - Female
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Event:
      foreignAlias: Disciplines_E
      class: Event
      refClass: EventDiscipline
      
Division:
  connection: doctrine
  tableName: division
  columns:
    discipline_id:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    category:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    weight:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Discipline:
      foreignAlias: Divisions_Disc

Event:
  columns:
    name: { type: string(255), default: null }
    description: { type: text }
    starts: { type: date }
    ends: { type: date }
    register_by: { type: date }
    token: { type: string(255) }

Profile:
  columns:
    event_id: { type: integer, notnull: true }
    sf_guard_user_id: { type: integer, notnull: true }
    first_name:  { type: string(255) }
    last_name: { type: string(255) }
    email_address: { type: string(255) }
    country: { type: string(255) }
  relations:
    Event:
      foreignAlias: Profiles_E
    sfGuardUser:
      local: sf_guard_user_id
      foreign: id

Type:
  columns:
    name: { type: string(255), notnull: true }

    
EventDiscipline:
  columns:
     event_id:
        type: integer
        primary: true
     discipline_id:
        type: integer
        primary: true
  relations:
    Event:
      foreignAlias: EventDisciplines
    Discipline:
      foreignAlias: EventDisciplines
