Attendee:
  connection: doctrine
  tableName: attendee
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    division_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    first_name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    last_name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    accomodation:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sharing_with:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    flight_datetime:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    flight_number:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Division:
      local: division_id
      foreign: id
      type: one
    Type:
      local: type_id
      foreign: id
      type: one
    Profile:
      local: id
      foreign: attendant_id
      type: one

Discipline:
  connection: doctrine
  tableName: discipline
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sex:
      type: enum(6)
      fixed: false
      unsigned: false
      values:
        - Male
        - Female
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Division:
      local: id
      foreign: discipline_id
      type: many
    EventDiscipline:
      local: id
      foreign: discipline_id
      type: many
Division:
  connection: doctrine
  tableName: division
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    discipline_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    category:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    weight:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Discipline:
      local: discipline_id
      foreign: id
      type: one
    Attendee:
      local: id
      foreign: division_id
      type: many
Event:
  connection: doctrine
  tableName: event
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    start:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    end:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    register_by:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    EventDiscipline:
      local: id
      foreign: event_id
      type: many
    Profile:
      local: id
      foreign: event_id
      type: one

EventDiscipline:
  connection: doctrine
  tableName: event_discipline
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    event_id:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    discipline_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Event:
      local: event_id
      foreign: id
      type: one
    Discipline:
      local: discipline_id
      foreign: id
      type: one

#TeamAdministrator:
  #relations:
    #Event:
      #local: event_id
      #foreign: id
      #type: one
    #Attendee:
      #local: id
      #foreign: team_administrator_id
      #type: many
Type:
  connection: doctrine
  tableName: type
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Attendee:
      local: id
      foreign: type_id
      type: many



Profile:
  columns:
    sf_guard_user_id: integer
    attendant_id: integer(8)
    event_id: integer(8)
    first_name: string(255)
    middle_name: string(255)
    last_name: string(255)
    email_address: string(255)
  relations:
    User:
      class: sfGuardUser
      foreignType: one
    Attendee:
      local: attendant_id
      foreign: id
      type: one
    Event:
      local: event_id
      foreign: id
      type: many


      