Attendee:
  connection: doctrine
  tableName: attendee
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    team_administrator_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    division_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    first_name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    last_name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    accomodation:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sharing_with:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    flight_datetime:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    flight_number:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    TeamAdministrator:
      local: team_administrator_id
      foreign: id
      type: one
    Division:
      local: division_id
      foreign: id
      type: one
    Type:
      local: type_id
      foreign: id
      type: one
Discipline:
  connection: doctrine
  tableName: discipline
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sex:
      type: enum(6)
      fixed: false
      unsigned: false
      values:
        - Male
        - Female
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Division:
      local: id
      foreign: discipline_id
      type: many
    EventDiscipline:
      local: id
      foreign: discipline_id
      type: many
Division:
  connection: doctrine
  tableName: division
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    discipline_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    category:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    weight:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Discipline:
      local: discipline_id
      foreign: id
      type: one
    Attendee:
      local: id
      foreign: division_id
      type: many
Event:
  connection: doctrine
  tableName: event
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    start:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    end:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    register_by:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    EventDiscipline:
      local: id
      foreign: event_id
      type: many
    TeamAdministrator:
      local: id
      foreign: event_id
      type: many
EventDiscipline:
  connection: doctrine
  tableName: event_discipline
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    event_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    discipline_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Event:
      local: event_id
      foreign: id
      type: one
    Discipline:
      local: discipline_id
      foreign: id
      type: one
TeamAdministrator:
  connection: doctrine
  tableName: team_administrator
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    event_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    first_name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    last_name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    username:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    password:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    email:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    team_name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Event:
      local: event_id
      foreign: id
      type: one
    Attendee:
      local: id
      foreign: team_administrator_id
      type: many
Type:
  connection: doctrine
  tableName: type
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Attendee:
      local: id
      foreign: type_id
      type: many
